import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header"
import Footer from "./components/Footer"
import AppContextProvider from './context/AppContext'
import {ToastContainer} from 'react-toastify'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tutor App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer position='bottom-right'/>
        <AppContextProvider>
        <Header/>
        {children}
        <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
